
.use_base_container: &use_base_container
  stage: ctf
  image: "${CI_REGISTRY_IMAGE}:latest"
services:
  - name: docker:dind
    command: ["dockerd", "--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock", "--dns=8.8.8.8", "--dns=8.8.4.4"]

.run_ctf: &run_ctf
  <<: *use_base_container
  before_script:
    - |
      for i in $(seq 1 5); do
        echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY_IMAGE && break || sleep 10

        echo "Retrying docker login ($i/5)..."
      done
  script:
    - unset DOCKER_HOST
    - pip3 uninstall pentestperf --yes  # remove old version
    - pip3 install -e .
    - msfrpcd -P cai > /dev/null 2>&1 &
    - |
      # Set additional environment variables if defined
      for var in $(compgen -e); do
        if [[ $var == CTF_* && -n ${!var} ]]; then
          export $var="${!var}"
        fi
      done
    - pytest -s tests/ctfs/test_generic_single_1.py  # NOTE: hardcoded file name
  artifacts:
    paths:
      - cai.png
      - cai.dot
      - logs
    expire_in: 1 month  # Retain the artifacts for 1 month
  tags:
    - p40
    - x86
    - one
  rules:
    - if: $CI_COMMIT_BRANCH
    #  when: on_success

# CTF Difficulty Levels:
# +------------+---------+---------------------------+-----------------------------+
# | Level      | Flags   | Target Audience          | Description                |
# +------------+---------+---------------------------+-----------------------------+
# | Very Easy  | 🚩      | High School Students     | Beginner / High School     |
# |            |         | Cybersecurity Beginners  | CTFs                       |
# +------------+---------+---------------------------+-----------------------------+
# | Easy       | 🚩🚩     | Individuals familiar     | Novice / Foundations       |
# |            |         | with basic security      | level challenges           |
# +------------+---------+---------------------------+-----------------------------+
# | Medium     | 🚩🚩🚩   | College Students         | Graduate Level /           |
# |            |         | Security Undergrads      | Collegiate CTFs            |
# +------------+---------+---------------------------+-----------------------------+
# | Hard       | 🚩🚩🚩🚩 | Working Pentesters       | Professional CTFs for      |
# |            |         | Security Professionals   | industry experts           |
# +------------+---------+---------------------------+-----------------------------+
# | Very Hard  | 🚩🚩🚩🚩🚩| Advanced Researchers     | Elite / Highly             |
# |            |          | Elite CTF Players        | Specialized challenges     |
# +------------+---------+---------------------------+-----------------------------+


################################################################################
# 🚩 Very Easy - Beginner / High School CTFs
# For high school students and cybersecurity beginners
################################################################################

🚩 baby_first | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: baby_first
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5

🚩 baby_third | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: baby_third
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5

🚩 chal1 | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: chal1
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5

🚩 kiddoctf | gpt-4o | i:
   <<: *run_ctf
   variables:
     CTF_NAME: kiddoctf
     CTF_MODEL: gpt-4o
     CTF_CHALLENGE: '01 linux i'
     CTF_RERUN: 5

🚩 kiddoctf | gpt-4o | ii:
   <<: *run_ctf
   variables:
     CTF_NAME: kiddoctf
     CTF_MODEL: gpt-4o
     CTF_CHALLENGE: '02 linux ii'
     CTF_RERUN: 5

🚩 kiddoctf | gpt-4o | iii:
   <<: *run_ctf
   variables:
     CTF_NAME: kiddoctf
     CTF_MODEL: gpt-4o
     CTF_CHALLENGE: '03 linux iii'
     CTF_RERUN: 5

🚩 kiddoctf | gpt-4o | iv:
   <<: *run_ctf
   variables:
     CTF_NAME: kiddoctf
     CTF_MODEL: gpt-4o
     CTF_CHALLENGE: '04 linux iv'
     CTF_RERUN: 5

🚩 picoctf_static_flag | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: picoctf_static_flag
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5

################################################################################
# 🚩🚩 Easy - Novice / Foundations
# For individuals familiar with basic cybersecurity concepts
################################################################################

🚩🚩 my_first_pwnie | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: my_first_pwnie
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩 picoctf_reversing_python | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: picoctf_reversing_python
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5
     CTF_INSIDE: false

################################################################################
# 🚩🚩🚩 Medium - Graduate Level / Collegiate CTFs
# For college students, cybersecurity undergraduates or graduates
################################################################################

🚩🚩🚩 android-dropper | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: android-dropper
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 blocky-nonsense | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: blocky-nonsense
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 bob | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: bob
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 breakvault | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: breakvault
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 hackableii | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: hackableii
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 linear_aggressor | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: linear_aggressor
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 lottery | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: lottery
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 mental-poker | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: mental
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 puffin | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: puffin
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 rox | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: picoctf_reversing_python
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5

🚩🚩🚩 tradinggame | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: tradinggame
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 xbow_five_twentyfour | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: xbow_five_twentyfour
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 xbow_four_twentyfour | gpt-4o:
   <<: *run_ctf
   variables:
     CTF_NAME: xbow_four_twentyfour
     CTF_MODEL: gpt-4o
     CTF_RERUN: 5
     CTF_INSIDE: false
